# Generated by Django 5.1.6 on 2025-03-14 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='reset_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='reset_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
