# Generated by Django 5.1.6 on 2025-03-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_artist_reset_code_producer_reset_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='user_followers', to='users.artist'),
        ),
        migrations.AddField(
            model_name='artist',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='user_following', to='users.artist'),
        ),
        migrations.AddField(
            model_name='artist',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='producer_followers', to='users.producer'),
        ),
        migrations.AddField(
            model_name='producer',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='producer_following', to='users.producer'),
        ),
        migrations.AddField(
            model_name='producer',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
