# Generated by Django 5.1.6 on 2025-03-25 06:10

import django.core.validators
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_artist_reset_code_producer_reset_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.profile_pic_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), users.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='producer',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.profile_pic_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), users.models.validate_image_size]),
        ),
    ]
