# Generated by Django 5.1.6 on 2025-03-25 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_artist_profile_picture_and_more'),
        ('users', '0003_artist_followers_artist_following_artist_location_and_more'),
    ]

    operations = [
    ]
