# Generated by Django 5.1.6 on 2025-03-26 01:30

import django.core.validators
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_20250325_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.cover_photo_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), users.models.validate_image_size]),
        ),
        migrations.AddField(
            model_name='producer',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.cover_photo_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), users.models.validate_image_size]),
        ),
    ]
