# Generated by Django 5.1.6 on 2025-03-28 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_collaborationrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborationrequest',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='collaborationrequest',
            name='sender',
        ),
        migrations.AddField(
            model_name='collaborationrequest',
            name='receiver_artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='users.artist'),
        ),
        migrations.AddField(
            model_name='collaborationrequest',
            name='receiver_producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='users.producer'),
        ),
        migrations.AddField(
            model_name='collaborationrequest',
            name='sender_artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='users.artist'),
        ),
        migrations.AddField(
            model_name='collaborationrequest',
            name='sender_producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='users.producer'),
        ),
    ]
