# Generated by Django 5.1.6 on 2025-03-28 06:29

from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_notification'),
    ]

    operations = [
        # For PostgreSQL - sets the sequence to start at 1,000,000
        migrations.RunSQL(
            sql="SELECT setval(pg_get_serial_sequence('users_producer', 'id'), 1000000, false);",
            reverse_sql="-- No reverse migration needed"
        ),
    ]
