# Generated by Django 5.1.6 on 2025-03-29 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_set_producer_id_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='post_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender_artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to='users.artist'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender_producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to='users.producer'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('collaboration_request', 'Collaboration Request'), ('collaboration_update', 'Collaboration Update'), ('system', 'System Notification'), ('like', 'Post Like'), ('comment', 'Post Comment')], max_length=50),
        ),
    ]
