# Generated by Django 5.1.6 on 2025-04-21 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_notification_post_id_notification_sender_artist_and_more'),
    ]

    operations = [
    ]
