# Generated by Django 5.1.6 on 2025-04-21 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_merge_20250421_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='collaboration_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producer',
            name='collaboration_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
