# Generated by Django 5.1.6 on 2025-04-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_user_artist_user_producer_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artist",
            name="user",
        ),
        migrations.RemoveField(
            model_name="producer",
            name="user",
        ),
        migrations.AddField(
            model_name="artist",
            name="collaboration_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="producer",
            name="collaboration_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
