# Generated by Django 5.1.6 on 2025-04-21 03:13

from django.db import migrations

def populate_collaboration_counts(apps, schema_editor):
    """
    Populate collaboration_count field for all existing users based on
    their accepted collaboration requests.
    """
    Artist = apps.get_model('users', 'Artist')
    Producer = apps.get_model('users', 'Producer')
    CollaborationRequest = apps.get_model('users', 'CollaborationRequest')

    # Process all artists
    for artist in Artist.objects.all():
        # Count accepted requests as sender
        sender_count = CollaborationRequest.objects.filter(
            sender_artist=artist,
            status='accepted'
        ).count()

        # Count accepted requests as receiver
        receiver_count = CollaborationRequest.objects.filter(
            receiver_artist=artist,
            status='accepted'
        ).count()

        # Update collaboration count
        artist.collaboration_count = sender_count + receiver_count
        artist.save(update_fields=['collaboration_count'])

    # Process all producers
    for producer in Producer.objects.all():
        # Count accepted requests as sender
        sender_count = CollaborationRequest.objects.filter(
            sender_producer=producer,
            status='accepted'
        ).count()

        # Count accepted requests as receiver
        receiver_count = CollaborationRequest.objects.filter(
            receiver_producer=producer,
            status='accepted'
        ).count()

        # Update collaboration count
        producer.collaboration_count = sender_count + receiver_count
        producer.save(update_fields=['collaboration_count'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_add_collaboration_count'),
    ]

    operations = [
        migrations.RunPython(populate_collaboration_counts, migrations.RunPython.noop),
    ]
