# Generated by Django 5.1.6 on 2025-04-24 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_remove_artist_user_remove_producer_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artist",
            name="collaboration_count",
        ),
        migrations.RemoveField(
            model_name="producer",
            name="collaboration_count",
        ),
    ]
