# Generated by Django 5.1.6 on 2025-04-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0002_userprofile_alter_project_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="project_images/"),
        ),
    ]
