# Generated by Django 5.1.6 on 2025-04-23 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0003_alter_project_image"),
        ("users", "0012_remove_artist_user_remove_producer_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="created_by",
        ),
        migrations.AddField(
            model_name="project",
            name="created_by_artist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="users.artist",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="created_by_producer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="users.producer",
            ),
        ),
    ]
