# Generated by Django 5.1.6 on 2025-04-16 17:47

import messaging.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_message_file_attachment_message_file_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file_attachment',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=messaging.models.get_attachment_path),
        ),
    ]
