# Generated by Django 5.1.6 on 2025-03-17 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
    ]
