# Generated by Django 5.1.6 on 2025-03-21 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20250317_1638'),
    ]

    operations = [
    ]
