# Generated by Django 5.1.6 on 2025-03-30 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_post_audio'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('post', 'user_id', 'user_type')},
        ),
    ]
